CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    id_users TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS below_track (
    id INTEGER PRIMARY KEY,
    'BTC-USD' INTEGER,
    'ETH-USD' INTEGER,
    'LTC-USD' INTEGER,
    'DOGE-USD' INTEGER,
    'ADA-USD' INTEGER,
    FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS higher_track (
    id INTEGER PRIMARY KEY,
   'BTC-USD' INTEGER,
   'ETH-USD' INTEGER,
   'LTC-USD' INTEGER,
   'DOGE-USD' INTEGER,
   'ADA-USD' INTEGER,
    FOREIGN KEY (id) REFERENCES users(id)
);